spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dreamcity?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: dreamcity
    password: Root@123
    jpa:
      hibernate:
        ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
      show-sql: true
  
  cache:
    type: redis
  redis:
    host: 156.236.69.200
    port: 6379
    database: 0
    password: 123456
    timeout: 0
    ssl: false
    jedis:
      pool:
        max-active: 300
        max-wait: -1
        max-idle: 300
        min-idle: 1

gate:
  zuul:
    url: http://localhost:8020/consumer/v1

props: #自定义的属性和值
  simpleProp: simplePropValue #单个值
  arrayProps: 1,2,3,4,5 #数组
  listProp1: #List集合
    - name: abc
      value: abcValue
    - name: efg
      value: efgValue
  listProp2:
    - config2Value1
    - config2Vavlue2
  mapProps: #Map集合
    key1: value1
    key2: value2



eureka:
  instance:
    hostname: 156.236.69.200
    instance-id: ${spring.application.name}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/,http://${eureka.instance.hostname}:9999/eureka/
