spring:
  #  cache:
  #    type: ehcache
  #    ehcache:
  #      config: classpath:ehcache.xml

  cache:
    type: redis
  redis:
    host: 103.107.237.198
    port: 6379
    database: 0
    password: 123456
    timeout: 0
    ssl: false
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 100
        min-idle: 1


  devtools:
    restart:
      #添加那个目录的文件需要restart
      additional-paths: src/main/java
      #排除那个目录的文件不需要restart
      exclude: static/**

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://103.107.237.198:3306/dreamcity?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    username: dreamcity
    password: Root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      initial-size: 5
      min-idle: 5
    tomcat:
      max-active: 20
      max-wait: 60000



#平台账户id，多个，都号隔开来自player_account表
dreamcity:
  #注册密码salt
  register:
    password:
      salt: DREAM_CITY_890@#$%
