spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dreamcity?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: dreamcity
    password: Root@123
    jpa:
      hibernate:
        ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
      show-sql: true


  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456
    timeout: 0
    ssl: false
    jedis:
      pool:
        max-active: 300
        max-wait: -1
        max-idle: 300
        min-idle: 1
  cloud:
    loadbalancer:
      retry:
        enabled: true

  devtools:
    restart:
      #添加那个目录的文件需要restart
      additional-paths: src/main/java
      #排除那个目录的文件不需要restart
      exclude: static/**



#注册密码salt
dreamcity:
  register:
    password:
      salt: DREAM_CITY_890@#$%


eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}
  client:
    eureka-server-read-timeout-seconds: 10
    eureka-connection-idle-timeout-seconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/,http://${eureka.instance.hostname}:9999/eureka/


