server:
  port: 8020
  servlet:
    context-path: /
spring:
  profiles:
    active: test
  application:
    name: city-gateway

  main:
    allow-bean-definition-overriding: true

zuul:
  routes:
    city-consumer:
      #url: localhost
      path: /consumer/**
      serviceId: city-consumer
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000


