server:
  port: 8020
  servlet:
    context-path: /
spring:
  profiles:
    active: ${spring.profiles.active}
  application:
    name: city-gateway

  main:
    allow-bean-definition-overriding: true

zuul:
  routes:
    city-consumer:
      #url: localhost
      path: /consumer/**
      serviceId: city-consumer
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000


#datasource
mybatis:
  type-aliases-package: com.dream.city.base.model.mapper
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

