server:
  port: 8030

spring:
  application:
    name: city-auth

  main:
    allow-bean-definition-overriding: true

mybatis:
  type-aliases-package: com.dream.city.domain.mapper
  mapper-locations: classpath:/mappers/*.xml

#eureka
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}-${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/, http://${eureka.instance.hostname}:9999/eureka/

auth:
  secret: oKKLJOoasdl