server:
  port: 8050
  servlet:
    context-path: /
spring:
  application:
    name: city-message
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dreamcity?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    username: dreamcity
    password: Root@123
  redis:
    host: 127.0.0.1
    password: 123456
    port: 6379
    database: 0
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/,http://${eureka.instance.hostname}:9999/eureka/


#datasource
mybatis:
  type-aliases-package: com.dream.city.domain.mapper
  mapper-locations: classpath:/mybatis/mappers/*.xml