tx-lcn:
  manager:
    admin-key: 123456
    host: 127.0.0.1
    port: 8070
  logger:
    enabled: true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dreamcity
    password: Root@123
    jdbc-url: jdbc:mysql://localhost:3306/dreamcity?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
  message:
    netty:
      attr-delay-time: 10000
logging:
  level:
    com:
      dream:
        city: debug
server:
  port: 79701
spring:
  application:
    name: tx-manager


