spring:
  redis:
    host: localhost
    database: 0
    password: 123456
    port: 6379

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.99:3306/city_quartz?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: dreamcity
    password: Root@123
    jpa:
      hibernate:
        ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
      show-sql: true

  devtools:
    restart:
      #添加那个目录的文件需要restart
      additional-paths: src/main/java
      #排除那个目录的文件不需要restart
      exclude: static/**

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/,http://${eureka.instance.hostname}:9999/eureka/


worker:
  channel:
    topics: topic1,topic2,topic3


tasks: "{listenerAdapterLogin: 'listenerAdapterLogin', listenerAdapterPlatTrans: 'listenerAdapterPlatTrans', listenerAdapterServerPush: 'listenerAdapterServerPush'}"