spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dreamcity?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: dreamcity
    password: Root@123
    jpa:
      hibernate:
        ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
      show-sql: true

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 123456
    timeout: 0
    ssl: false
    jedis:
      pool:
        max-active: 300
        max-idle: 300
        max-wait: -1
        min-idle: 1
    
    
    
  
# 打印日志
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG

#datasource
mybatis:
  type-aliases-package: com.dream.city.base.model.mapper
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



worker:
  channel:
    topics: topic1,topic2,topic3


tasks: "{listenerAdapterLogin: 'listenerAdapterLogin', listenerAdapterPlatTrans: 'listenerAdapterPlatTrans', listenerAdapterServerPush: 'listenerAdapterServerPush'}"




eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}-${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/,http://${eureka.instance.hostname}:9999/eureka/