server:
  port: 9020

spring:
  application:
    name: city-property
  profiles:
    active: test
  main:
    allow-bean-definition-overriding: true



#datasource
mybatis:
  type-aliases-package: com.dream.city.base.model.mapper
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




