server:
  port: 8280
  servlet:
    context-path: /

spring:
  application:
    name: city-tree
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev

#eureka
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/, http://${eureka.instance.hostname}:9999/eureka/



mybatis:
  type-aliases-package: com.dream.city.base.model.mapper
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


