server:
  port: 8180
  servlet:
    context-path: /

spring:
  application:
    name: city-set
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true



#datasource
mybatis:
  type-aliases-package: com.dream.city.base.model.mapper
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




