server:
  port: 8062

spring:
  application:
    name: city-set
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dreamcity?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useSSL=false
    username: dreamcity
    password: Root@123

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}-${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8888/eureka/,http://${eureka.instance.hostname}:9999/eureka/


#datasource
mybatis:
  type-aliases-package: com.dream.city.domain.mapper
  mapper-locations: classpath:/mybatis/mappers/*.xml




