spring:
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456
    timeout: 0
    ssl: false
    jedis:
      pool:
        max-active: 300
        max-wait: -1
        max-idle: 300
        min-idle: 1
  cloud:
    loadbalancer:
      retry:
        enabled: true

#注册密码salt
dreamcity:
  register:
    password:
      salt: DREAM_CITY_890@#$%

  #平台账户id，多个，都号隔开来自player_account表
  platform:
    account:
      accIds: 888888888,999999999

eureka:
  client:
    eureka-server-read-timeout-seconds: 10
    eureka-connection-idle-timeout-seconds: 5
