spring:
  main:
    allow-bean-definition-overriding: true
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 123456
    timeout: 0
    ssl: false
    jedis:
      pool:
        max-active: 300
        max-wait: -1
        max-idle: 300
        min-idle: 1

#注册密码salt
dreamcity:
  register:
    password:
      salt: DREAM_CITY_890@#$%






