server:
  port: 8040
  servlet:
    context-path: /v1

spring:
  application:
    name: city-consumer

  profiles:
    active: ${spring.profiles.active}

  main:
    allow-bean-definition-overriding: true



#datasource
mybatis:
  type-aliases-package: com.dream.city.base.model.mapper
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#全局配置
# 请求连接的超时时间 默认的时间为 1 秒
# 请求处理的超时时间
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
feign:
  client:
    config:
      default:
          connectTimeout: 5000
          readTimeout: 5000
          loggerLevel: basic
